version: "2.2"

services:
 redis-master:
  image: changel/redis:3.2.12
  restart: always
  container_name: redis-master

  environment:
    - "SET_REDIS_REQUIREPASS=88888888"
  networks:
      user-define:
        aliases:
         - redis-master
  volumes:
    - /data/redis/master:/data

 redis-slave-1:
  image: changel/redis:3.2.12
  restart: always
  container_name: redis-slave-1

  environment:
    - "SET_REDIS_REQUIREPASS=88888888"
    - "SET_REDIS_MASTERAUTH=88888888"
    - "SET_REDIS_SLAVEOF=redis-master 6379"
  networks:
    - user-define
  volumes:
    - /data/redis/slave-1:/data

 redis-slave-2:
  image: changel/redis:3.2.12
  restart: always
  container_name: redis-slave-2

  environment:
    - "SET_REDIS_REQUIREPASS=88888888"
    - "SET_REDIS_MASTERAUTH=88888888"
    - "SET_REDIS_SLAVEOF=redis-master 6379"
  networks:
    - user-define
  volumes:
    - /data/redis/slave-2:/data

networks:
  user-define: