version: "2.2"
services:
 vsftp:
  image: changel.cn/vsftp:3.0.3
  restart: always
  container_name: vsftp

  ports:
   - "20-21:20-21"
   - "50000-50010:50000-50010"
  volumes:
   - /data/vsftp:/data
