version: "2.2"

services:
 mongo-express:
  image: changel.cn/mongo-express:0.45
  restart: always
  container_name: mongo-express

  ports:
   - 8081:8081
  networks:
    - "mongo"
  environment:
   - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
   - ME_CONFIG_MONGODB_ADMINPASSWORD=88888888
   #- ME_CONFIG_MONGODB_SERVER=mongo
   #- "ME_CONFIG_BASICAUTH_USERNAME=admin"
   #- "ME_CONFIG_BASICAUTH_PASSWORD=pass"

networks:
  mongo:
    external: true