FROM node:10.3.0-alpine

MAINTAINER changel <changel@changel.cn>

# install timezone
RUN set -ex \
  && apk add --no-cache tzdata \
  && ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime

ENV MONGO_EXPRESS=0.45.0 \
    VCAP_APP_HOST=0.0.0.0 \
    ME_CONFIG_MONGODB_SERVER="mongo" \
    ME_CONFIG_MONGODB_ENABLE_ADMIN="true"


RUN set -ex \
    && echo '/usr/local/bin/npm --registry=https://registry.npm.taobao.org --cache=/tmp/cache --disturl=https://npm.taobao.org/dist --userconfig=$HOME/.cnpmrc $@' >/usr/bin/cnpm \
    && chmod 755 /usr/bin/cnpm \
    && cnpm install -g mongo-express@$MONGO_EXPRESS

expose 8081

CMD mongo-express