version: "2.2"

services:
 rocketmq-server-dev:
  image: foxiswho/rocketmq:4.8.0
  restart: always
  container_name: rocketmq-server-dev

  logging:
    driver: json-file
    options:
      max-size: 10m
  ports:
     - "9876:9876"
  networks:
     - "jyt-default"
  command: "sh mqnamesrv"
  environment:
     - "JAVA_OPT_EXT=-Xms512M -Xmx512M -Xmn128m"
  volumes:
   - /data/rocketmq/server-dev:/home/rocketmq/logs
 
 rocketmq-broker-dev:
  image: foxiswho/rocketmq:4.8.0
  restart: always
  container_name: rocketmq-broker-dev

  logging:
    driver: json-file
    options:
      max-size: 10m
  ports:
     - "10911:10911"
     - "10912:10912"
     - "10909:10909"
  networks:
     - "jyt-default"
  command: "sh mqbroker -c /home/rocketmq/conf/broker.conf"
  environment:
     - "JAVA_OPT_EXT=-Xms512M -Xmx512M -Xmn128m"
     - "NAMESRV_ADDR=rocketmq-server-dev:9876"
  volumes:
   - /data/rocketmq/broker-dev/logs:/home/rocketmq/logs
   - /data/rocketmq/broker-dev/store:/home/rocketmq/store
   - /data/rocketmq/broker-dev/conf:/home/rocketmq/conf
 rocketmq-console-dev:
  image: styletang/rocketmq-console-ng
  restart: always
  container_name: rocketmq-console-dev

  logging:
    driver: json-file
    options:
      max-size: 10m
  ports:
     - "8088:8080"
  networks:
     - "jyt-default"
  environment:
     - "JAVA_OPTS=-Drocketmq.namesrv.addr=rocketmq-server-dev:9876 -Dcom.rocketmq.sendMessageWithVIPChannel=false"

networks:
 jyt-default:
   external: true