[template]
src = "nginx.tmpl"
dest = "/etc/nginx/nginx.conf"
owner = "nginx"
mode = "0644"
prefix="/services/nginx"
keys = [
  "/",
]
check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
reload_cmd = "/usr/sbin/nginx -s reload"