version: "2.0"
services:
 nginx:
  image: changel/nginx:1.15
  restart: always
  container_name: nginx

  ports:
   - "80:80"
  environment:
   - "SET_CONFD_ENABLE=yes"
   - "SET_ETCD_NODES=http://etcd:2379"
  networks:
   - sys-default

 etcd:
  image: changel/etcd:3.3.13
  restart: always
  container_name: etcd

  ports:
   - "2379:2379"
  environment:
   - "ETCD_NAME=etcd"
  volumes:
   - /data/etcd/etcd:/var/lib/etcd
  networks:
   - sys-default

networks:
  sys-default:
    external: true
