zabbix:
  image: zabbix:v1
  restart: always
  container_name: zabbix

  net: "container:dbzabbix"
  volumes:
   - /data/zabbix:/usr/local/zabbix/etc

webzabbix:
  image: php:zabbix
  restart: always
  container_name: web-zabbix

  net: "container:dbzabbix"

#you must inport date at first
dbzabbix:
  image: mysql:v1
  restart: always
  container_name: db-zabbix
  
  ports: 
   - "10051:10051"
   - "8585:80"
  volumes:
   - /data/mysql/zabbix:/var/lib/mysql
